version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conference_db
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./migrate
    container_name: migrate
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./auth-server/app:/app/auth-server/app
      - ./protected-api/app:/app/protected-api/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/conference_db
      - PYTHONPATH=/app
      - SECRET_KEY=default_secret
      - ALGORITHM=HS256
    working_dir: /app
    entrypoint: ["alembic", "upgrade", "head"]
    depends_on:
      - db

  auth-server:
    build: ./auth-server
    container_name: auth-server
    ports:
      - "8000:8000"
    env_file:
      - ./auth-server/.env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/conference_db
      - PYTHONPATH=/app
    depends_on:
      - db
      - migrate

  protected-api:
    build: ./protected-api
    container_name: protected-api
    ports:
      - "8001:8000"
    env_file:
      - ./protected-api/.env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/conference_db
      - PYTHONPATH=/app
    depends_on:
      - db
      - migrate

volumes:
  db-data:
