"""initial migration

Revision ID: 754a9391b05f
Revises: 
Create Date: 2024-06-10 16:31:03.209894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754a9391b05f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendees_email'), 'attendees', ['email'], unique=True)
    op.create_index(op.f('ix_attendees_id'), 'attendees', ['id'], unique=False)
    op.create_index(op.f('ix_attendees_name'), 'attendees', ['name'], unique=False)
    op.create_table('conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conferences_id'), 'conferences', ['id'], unique=False)
    op.create_index(op.f('ix_conferences_title'), 'conferences', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_id'), 'speakers', ['id'], unique=False)
    op.create_index(op.f('ix_speakers_name'), 'speakers', ['name'], unique=False)
    op.create_table('conference_speakers',
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_speakers')
    op.drop_index(op.f('ix_speakers_name'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_conferences_title'), table_name='conferences')
    op.drop_index(op.f('ix_conferences_id'), table_name='conferences')
    op.drop_table('conferences')
    op.drop_index(op.f('ix_attendees_name'), table_name='attendees')
    op.drop_index(op.f('ix_attendees_id'), table_name='attendees')
    op.drop_index(op.f('ix_attendees_email'), table_name='attendees')
    op.drop_table('attendees')
    # ### end Alembic commands ###
