"""attendees

Revision ID: 7ed524095731
Revises: 754a9391b05f
Create Date: 2024-06-10 16:51:35.459465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed524095731'
down_revision: Union[str, None] = '754a9391b05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_attendees',
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], )
    )
    op.alter_column('conferences', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conferences', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('conference_attendees')
    # ### end Alembic commands ###
