"""Add title and description to conferences

Revision ID: 9b2d823d38b2
Revises: 
Create Date: 2024-06-10 14:28:19.338255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2d823d38b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('title', sa.String(), nullable=True))
    op.add_column('conferences', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_conferences_name', table_name='conferences')
    op.create_index(op.f('ix_conferences_title'), 'conferences', ['title'], unique=False)
    op.drop_column('conferences', 'name')
    op.drop_column('conferences', 'location')
    op.add_column('speakers', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_speakers_name'), 'speakers', ['name'], unique=False)
    op.drop_constraint('speakers_conference_id_fkey', 'speakers', type_='foreignkey')
    op.drop_column('speakers', 'topic')
    op.drop_column('speakers', 'conference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('conference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('speakers', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('speakers_conference_id_fkey', 'speakers', 'conferences', ['conference_id'], ['id'])
    op.drop_index(op.f('ix_speakers_name'), table_name='speakers')
    op.drop_column('speakers', 'name')
    op.add_column('conferences', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conferences', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conferences_title'), table_name='conferences')
    op.create_index('ix_conferences_name', 'conferences', ['name'], unique=False)
    op.drop_column('conferences', 'description')
    op.drop_column('conferences', 'title')
    # ### end Alembic commands ###
